name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
 
      - name: validate if our value is the same as our secret
        env:
          SECRET_STRING : ${{ secrets.SECRET_STRING }}
        run: |
          if [ ${SECRET_STRING} == "12345" ]
            then
              echo "the secret (${SECRET_STRING}) has been validated"
            else
              echo "the string that you provided is not correct"
          fi
